#!/usr/bin/env bash
# Update the package
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/.*listen 80.*/listen 80;/g' /etc/nginx/sites-available/default
sudo /etc/init.d/nginx reload
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
