#!/usr/bin/env bash
# script to setup a HAProxy load balancer
# edit config file
server_config=\
"
frontend  loadbalancing_alx
	bind *:80
	default_backend alx_backend
backend backend_alx
        balance roundrobin
        server 107952-web-01 54.237.208.45:80
        server 107952-web-02 100.25.10.122:80
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
