#!/usr/bin/env bash
# This script checks if a host is on the network.

# Check if an argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the argument
ip_address="$1"

# Perform the ping (5 times)
ping -c 5 "$ip_address"
