#!/usr/bin/env bash
# Finding out what is keeping nginx installation from listening to port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
