#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

count=1
while [[ $count -le 10 ]]
do
	if [[ $count == 4 ]]
	then
		echo "bad luck"
	elif [[ $count == 8 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi # close the if block
	((count++))
done
