#!/usr/bin/env bash
# This script is displaying the content of the current directory

for file in ./*
do
	if [[ $file != ^\..* ]] #check if the file is not a hidden file
	then
		name=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name"
	fi
done
